# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'extendedCalc.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(584, 561)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.centralwidget.setFont(font)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.cos_button = QtWidgets.QPushButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cos_button.sizePolicy().hasHeightForWidth())
        self.cos_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.cos_button.setFont(font)
        self.cos_button.setObjectName("cos_button")
        self.gridLayout_6.addWidget(self.cos_button, 1, 1, 1, 1)
        self.tan_button = QtWidgets.QPushButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tan_button.sizePolicy().hasHeightForWidth())
        self.tan_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.tan_button.setFont(font)
        self.tan_button.setObjectName("tan_button")
        self.gridLayout_6.addWidget(self.tan_button, 1, 2, 1, 1)
        self.cotan_button = QtWidgets.QPushButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cotan_button.sizePolicy().hasHeightForWidth())
        self.cotan_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cotan_button.setFont(font)
        self.cotan_button.setObjectName("cotan_button")
        self.gridLayout_6.addWidget(self.cotan_button, 1, 3, 1, 1)
        self.sin_button = QtWidgets.QPushButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sin_button.sizePolicy().hasHeightForWidth())
        self.sin_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.sin_button.setFont(font)
        self.sin_button.setObjectName("sin_button")
        self.gridLayout_6.addWidget(self.sin_button, 1, 0, 1, 1)
        self.del_button = QtWidgets.QPushButton(self.frame_4)
        self.del_button.setObjectName("del_button")
        self.gridLayout_6.addWidget(self.del_button, 2, 0, 1, 1)
        self.clear_button = QtWidgets.QPushButton(self.frame_4)
        self.clear_button.setObjectName("clear_button")
        self.gridLayout_6.addWidget(self.clear_button, 2, 1, 1, 1)
        self.fromMem_button = QtWidgets.QPushButton(self.frame_4)
        self.fromMem_button.setObjectName("fromMem_button")
        self.gridLayout_6.addWidget(self.fromMem_button, 2, 2, 1, 1)
        self.toMem_button = QtWidgets.QPushButton(self.frame_4)
        self.toMem_button.setObjectName("toMem_button")
        self.gridLayout_6.addWidget(self.toMem_button, 2, 3, 1, 1)
        self.opparen_button = QtWidgets.QPushButton(self.frame_4)
        self.opparen_button.setObjectName("opparen_button")
        self.gridLayout_6.addWidget(self.opparen_button, 3, 0, 1, 1)
        self.clparen_button = QtWidgets.QPushButton(self.frame_4)
        self.clparen_button.setObjectName("clparen_button")
        self.gridLayout_6.addWidget(self.clparen_button, 3, 1, 1, 1)
        self.pow_button = QtWidgets.QPushButton(self.frame_4)
        self.pow_button.setObjectName("pow_button")
        self.gridLayout_6.addWidget(self.pow_button, 3, 2, 1, 1)
        self.mod_button = QtWidgets.QPushButton(self.frame_4)
        self.mod_button.setObjectName("mod_button")
        self.gridLayout_6.addWidget(self.mod_button, 3, 3, 1, 1)
        self.gridLayout_3.addWidget(self.frame_4, 2, 0, 1, 2)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.scrollArea.setFont(font)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 564, 69))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.scrollAreaWidgetContents.setFont(font)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.result_field = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.result_field.sizePolicy().hasHeightForWidth())
        self.result_field.setSizePolicy(sizePolicy)
        self.result_field.setBaseSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.result_field.setFont(font)
        self.result_field.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.result_field.setObjectName("result_field")
        self.verticalLayout.addWidget(self.result_field)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_3.addWidget(self.scrollArea, 0, 0, 2, 3)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.frame_2.setFont(font)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.result_button = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.result_button.sizePolicy().hasHeightForWidth())
        self.result_button.setSizePolicy(sizePolicy)
        self.result_button.setObjectName("result_button")
        self.gridLayout_2.addWidget(self.result_button, 4, 0, 1, 1)
        self.minus_button = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minus_button.sizePolicy().hasHeightForWidth())
        self.minus_button.setSizePolicy(sizePolicy)
        self.minus_button.setObjectName("minus_button")
        self.gridLayout_2.addWidget(self.minus_button, 1, 0, 1, 1)
        self.mul_button = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mul_button.sizePolicy().hasHeightForWidth())
        self.mul_button.setSizePolicy(sizePolicy)
        self.mul_button.setObjectName("mul_button")
        self.gridLayout_2.addWidget(self.mul_button, 3, 0, 1, 1)
        self.plus_button = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plus_button.sizePolicy().hasHeightForWidth())
        self.plus_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.plus_button.setFont(font)
        self.plus_button.setObjectName("plus_button")
        self.gridLayout_2.addWidget(self.plus_button, 0, 0, 1, 1)
        self.division_button = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.division_button.sizePolicy().hasHeightForWidth())
        self.division_button.setSizePolicy(sizePolicy)
        self.division_button.setObjectName("division_button")
        self.gridLayout_2.addWidget(self.division_button, 2, 0, 1, 1)
        self.dot_button = QtWidgets.QPushButton(self.frame_2)
        self.dot_button.setObjectName("dot_button")
        self.gridLayout_2.addWidget(self.dot_button, 5, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame_2, 3, 1, 1, 1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.frame.setFont(font)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.one_button = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.one_button.sizePolicy().hasHeightForWidth())
        self.one_button.setSizePolicy(sizePolicy)
        self.one_button.setObjectName("one_button")
        self.gridLayout.addWidget(self.one_button, 3, 0, 1, 1)
        self.three_button = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.three_button.sizePolicy().hasHeightForWidth())
        self.three_button.setSizePolicy(sizePolicy)
        self.three_button.setObjectName("three_button")
        self.gridLayout.addWidget(self.three_button, 3, 2, 1, 1)
        self.zero_button = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zero_button.sizePolicy().hasHeightForWidth())
        self.zero_button.setSizePolicy(sizePolicy)
        self.zero_button.setObjectName("zero_button")
        self.gridLayout.addWidget(self.zero_button, 4, 1, 1, 1)
        self.six_button = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.six_button.sizePolicy().hasHeightForWidth())
        self.six_button.setSizePolicy(sizePolicy)
        self.six_button.setObjectName("six_button")
        self.gridLayout.addWidget(self.six_button, 2, 0, 1, 1)
        self.two_button = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.two_button.sizePolicy().hasHeightForWidth())
        self.two_button.setSizePolicy(sizePolicy)
        self.two_button.setObjectName("two_button")
        self.gridLayout.addWidget(self.two_button, 3, 1, 1, 1)
        self.five_button = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.five_button.sizePolicy().hasHeightForWidth())
        self.five_button.setSizePolicy(sizePolicy)
        self.five_button.setObjectName("five_button")
        self.gridLayout.addWidget(self.five_button, 2, 1, 1, 1)
        self.nine_button = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nine_button.sizePolicy().hasHeightForWidth())
        self.nine_button.setSizePolicy(sizePolicy)
        self.nine_button.setObjectName("nine_button")
        self.gridLayout.addWidget(self.nine_button, 1, 2, 1, 1)
        self.four_button = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.four_button.sizePolicy().hasHeightForWidth())
        self.four_button.setSizePolicy(sizePolicy)
        self.four_button.setObjectName("four_button")
        self.gridLayout.addWidget(self.four_button, 2, 2, 1, 1)
        self.seven_button = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.seven_button.sizePolicy().hasHeightForWidth())
        self.seven_button.setSizePolicy(sizePolicy)
        self.seven_button.setObjectName("seven_button")
        self.gridLayout.addWidget(self.seven_button, 1, 0, 1, 1)
        self.eight_button = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eight_button.sizePolicy().hasHeightForWidth())
        self.eight_button.setSizePolicy(sizePolicy)
        self.eight_button.setObjectName("eight_button")
        self.gridLayout.addWidget(self.eight_button, 1, 1, 1, 1)
        self.gridLayout_3.addWidget(self.frame, 3, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.formLayout = QtWidgets.QFormLayout(self.frame_3)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setHorizontalSpacing(0)
        self.formLayout.setVerticalSpacing(2)
        self.formLayout.setObjectName("formLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame_3)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.exp_button = QtWidgets.QPushButton(self.groupBox_2)
        self.exp_button.setObjectName("exp_button")
        self.gridLayout_8.addWidget(self.exp_button, 2, 0, 1, 1)
        self.factorial_button = QtWidgets.QPushButton(self.groupBox_2)
        self.factorial_button.setObjectName("factorial_button")
        self.gridLayout_8.addWidget(self.factorial_button, 1, 0, 1, 1)
        self.sqrt_button = QtWidgets.QPushButton(self.groupBox_2)
        self.sqrt_button.setObjectName("sqrt_button")
        self.gridLayout_8.addWidget(self.sqrt_button, 1, 1, 1, 1)
        self.atg_button = QtWidgets.QPushButton(self.groupBox_2)
        self.atg_button.setObjectName("atg_button")
        self.gridLayout_8.addWidget(self.atg_button, 4, 0, 1, 1)
        self.ctgh_button = QtWidgets.QPushButton(self.groupBox_2)
        self.ctgh_button.setObjectName("ctgh_button")
        self.gridLayout_8.addWidget(self.ctgh_button, 6, 1, 1, 1)
        self.asin_button = QtWidgets.QPushButton(self.groupBox_2)
        self.asin_button.setObjectName("asin_button")
        self.gridLayout_8.addWidget(self.asin_button, 3, 0, 1, 1)
        self.cosh_button = QtWidgets.QPushButton(self.groupBox_2)
        self.cosh_button.setObjectName("cosh_button")
        self.gridLayout_8.addWidget(self.cosh_button, 5, 1, 1, 1)
        self.log_e_button = QtWidgets.QPushButton(self.groupBox_2)
        self.log_e_button.setObjectName("log_e_button")
        self.gridLayout_8.addWidget(self.log_e_button, 0, 1, 1, 1)
        self.log_ten_button = QtWidgets.QPushButton(self.groupBox_2)
        self.log_ten_button.setObjectName("log_ten_button")
        self.gridLayout_8.addWidget(self.log_ten_button, 0, 0, 1, 1)
        self.atgh_button = QtWidgets.QPushButton(self.groupBox_2)
        self.atgh_button.setObjectName("atgh_button")
        self.gridLayout_8.addWidget(self.atgh_button, 8, 0, 1, 1)
        self.actgh_button = QtWidgets.QPushButton(self.groupBox_2)
        self.actgh_button.setObjectName("actgh_button")
        self.gridLayout_8.addWidget(self.actgh_button, 8, 1, 1, 1)
        self.tgh_button = QtWidgets.QPushButton(self.groupBox_2)
        self.tgh_button.setObjectName("tgh_button")
        self.gridLayout_8.addWidget(self.tgh_button, 6, 0, 1, 1)
        self.actg_button = QtWidgets.QPushButton(self.groupBox_2)
        self.actg_button.setObjectName("actg_button")
        self.gridLayout_8.addWidget(self.actg_button, 4, 1, 1, 1)
        self.sinh_button = QtWidgets.QPushButton(self.groupBox_2)
        self.sinh_button.setObjectName("sinh_button")
        self.gridLayout_8.addWidget(self.sinh_button, 5, 0, 1, 1)
        self.acos_button = QtWidgets.QPushButton(self.groupBox_2)
        self.acos_button.setObjectName("acos_button")
        self.gridLayout_8.addWidget(self.acos_button, 3, 1, 1, 1)
        self.asinh_button = QtWidgets.QPushButton(self.groupBox_2)
        self.asinh_button.setObjectName("asinh_button")
        self.gridLayout_8.addWidget(self.asinh_button, 7, 0, 1, 1)
        self.acosh_button = QtWidgets.QPushButton(self.groupBox_2)
        self.acosh_button.setObjectName("acosh_button")
        self.gridLayout_8.addWidget(self.acosh_button, 7, 1, 1, 1)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.groupBox_2)
        self.gridLayout_3.addWidget(self.frame_3, 2, 2, 2, 1)
        self.gridLayout_3.setRowStretch(0, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 584, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuOptions = QtWidgets.QMenu(self.menuBar)
        self.menuOptions.setObjectName("menuOptions")
        MainWindow.setMenuBar(self.menuBar)
        self.actionRegular = QtWidgets.QAction(MainWindow)
        self.actionRegular.setCheckable(True)
        self.actionRegular.setChecked(False)
        self.actionRegular.setObjectName("actionRegular")
        self.actionExtended = QtWidgets.QAction(MainWindow)
        self.actionExtended.setCheckable(True)
        self.actionExtended.setChecked(True)
        self.actionExtended.setObjectName("actionExtended")
        self.menuOptions.addAction(self.actionRegular)
        self.menuOptions.addAction(self.actionExtended)
        self.menuBar.addAction(self.menuOptions.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AwesomeCalculator"))
        self.cos_button.setText(_translate("MainWindow", "cos"))
        self.tan_button.setText(_translate("MainWindow", "tg"))
        self.cotan_button.setText(_translate("MainWindow", "ctg"))
        self.sin_button.setText(_translate("MainWindow", "sin"))
        self.del_button.setText(_translate("MainWindow", "del"))
        self.clear_button.setText(_translate("MainWindow", "C"))
        self.fromMem_button.setText(_translate("MainWindow", "RM"))
        self.toMem_button.setText(_translate("MainWindow", "M"))
        self.opparen_button.setText(_translate("MainWindow", "("))
        self.clparen_button.setText(_translate("MainWindow", ")"))
        self.pow_button.setText(_translate("MainWindow", "^"))
        self.mod_button.setText(_translate("MainWindow", "%"))
        self.result_field.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe Print\'; font-size:15pt; font-weight:600; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.result_field.setPlaceholderText(_translate("MainWindow", "0"))
        self.result_button.setText(_translate("MainWindow", "="))
        self.minus_button.setText(_translate("MainWindow", "-"))
        self.mul_button.setText(_translate("MainWindow", "*"))
        self.plus_button.setText(_translate("MainWindow", "+"))
        self.division_button.setText(_translate("MainWindow", "/"))
        self.dot_button.setText(_translate("MainWindow", "."))
        self.one_button.setText(_translate("MainWindow", "1"))
        self.three_button.setText(_translate("MainWindow", "3"))
        self.zero_button.setText(_translate("MainWindow", "0"))
        self.six_button.setText(_translate("MainWindow", "6"))
        self.two_button.setText(_translate("MainWindow", "2"))
        self.five_button.setText(_translate("MainWindow", "5"))
        self.nine_button.setText(_translate("MainWindow", "9"))
        self.four_button.setText(_translate("MainWindow", "4"))
        self.seven_button.setText(_translate("MainWindow", "7"))
        self.eight_button.setText(_translate("MainWindow", "8"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Math"))
        self.exp_button.setText(_translate("MainWindow", "Exp"))
        self.factorial_button.setText(_translate("MainWindow", "n!"))
        self.sqrt_button.setText(_translate("MainWindow", "sqrt"))
        self.atg_button.setText(_translate("MainWindow", "atg"))
        self.ctgh_button.setText(_translate("MainWindow", "ctgh"))
        self.asin_button.setText(_translate("MainWindow", "asin"))
        self.cosh_button.setText(_translate("MainWindow", "cosh"))
        self.log_e_button.setText(_translate("MainWindow", "ln"))
        self.log_ten_button.setText(_translate("MainWindow", "log"))
        self.atgh_button.setText(_translate("MainWindow", "atgh"))
        self.actgh_button.setText(_translate("MainWindow", "actgh"))
        self.tgh_button.setText(_translate("MainWindow", "tgh"))
        self.actg_button.setText(_translate("MainWindow", "actg"))
        self.sinh_button.setText(_translate("MainWindow", "sinh"))
        self.acos_button.setText(_translate("MainWindow", "acos"))
        self.asinh_button.setText(_translate("MainWindow", "asinh"))
        self.acosh_button.setText(_translate("MainWindow", "acosh"))
        self.menuOptions.setTitle(_translate("MainWindow", "Options"))
        self.actionRegular.setText(_translate("MainWindow", "Regular"))
        self.actionExtended.setText(_translate("MainWindow", "Extended"))

