

/*
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.
*/

fun findTheDifference(s: String, t: String): Char {
  val freqs = IntArray(26)
  for (i in t.indices) {
    if (i < s.length) freqs[s[i] - 'a']++
    freqs[t[i] - 'a']--
  }
        
  for (i in freqs.indices) {
    if (freqs[i] != 0) return 'a' + i
  }
        
  return 'a'
}
